# Generated by Django 5.0.1 on 2024-01-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlyissues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyissues',
            name='pdf',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='monthlyissues',
            name='thumbnail',
            field=models.ImageField(upload_to='media'),
        ),
    ]
