# Generated by Django 5.0.1 on 2024-01-25 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlyissues', '0003_alter_monthlyissues_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyissues',
            name='pdf',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='file')),
                ('monthlyissue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='monthlyissues.monthlyissues')),
            ],
        ),
    ]
