# Generated by Django 5.0.1 on 2024-01-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthlyissues', '0004_remove_monthlyissues_pdf_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Photo',
        ),
    ]
