# Generated by Django 5.0.1 on 2024-04-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
