# Generated by Django 5.0.1 on 2024-01-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlyissues', '0006_page_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyissues',
            name='issue_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='monthlyissues',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='monthlyissues',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
