# Generated by Django 5.0.1 on 2024-01-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlyissues', '0002_alter_monthlyissues_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyissues',
            name='pdf',
            field=models.FileField(upload_to='file'),
        ),
        migrations.AlterField(
            model_name='monthlyissues',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail'),
        ),
    ]
