# Generated by Django 5.0.1 on 2024-01-25 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlyissues', '0005_rename_images_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ImageField(upload_to='file')),
                ('monthlyissue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pages', to='monthlyissues.monthlyissues')),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
